export const projetosData = [
  {
    titulo: "Centro Comunitário",
    descricao: "Espaço multiuso para reuniões e eventos.",
    custo: "12.000.000 Kz",
    localizacao: "Palanca, Luanda",
    estado: "execução",
    dataCriacao: "2025-01-15",
    dataTermino: "2025-12-20",
    anexos: ["Planta", "Orçamento", "Fotos"],
  },
  {
    titulo: "Escola Primária",
    descricao: "Reforma completa da escola.",
    custo: "8.500.000 Kz",
    localizacao: "Cazenga, Luanda",
    estado: "aprovado",
    dataCriacao: "2025-03-10",
    dataTermino: "2025-09-30",
    anexos: ["Relatório", "Orçamento", "Imagens"],
  },
  {
    titulo: "Sistema de Água",
    descricao: "Rede de abastecimento de água.",
    custo: "6.200.000 Kz",
    localizacao: "Sambizanga, Luanda",
    estado: "pendente",
    dataCriacao: "2025-04-05",
    dataTermino: "2025-10-15",
    anexos: ["Estudo", "Mapa", "Orçamento"],
  },
  {
    titulo: "Pavimentação Urbana",
    descricao: "Melhoria das vias locais.",
    custo: "15.000.000 Kz",
    localizacao: "Benfica, Luanda",
    estado: "parado",
    dataCriacao: "2024-11-20",
    dataTermino: "2025-08-30",
    anexos: ["Projeto", "Relatório", "Orçamento"],
  },
  {
    titulo: "Posto Médico",
    descricao: "Unidade básica de saúde.",
    custo: "9.800.000 Kz",
    localizacao: "Viana, Luanda",
    estado: "cancelado",
    dataCriacao: "2025-02-01",
    dataTermino: "2025-07-01",
    anexos: ["Planta", "Licença", "Orçamento"],
  },
  {
    titulo: "Espaço Cultural",
    descricao: "Centro com auditório e biblioteca.",
    custo: "11.500.000 Kz",
    localizacao: "Maianga, Luanda",
    estado: "finalizado",
    dataCriacao: "2024-06-15",
    dataTermino: "2025-03-10",
    anexos: ["Fotos", "Relatório", "Orçamento"],
  },
  {
    titulo: "Reciclagem Comunitária",
    descricao: "Educação ambiental e coleta seletiva.",
    custo: "3.200.000 Kz",
    localizacao: "Rangel, Luanda",
    estado: "devolvido",
    dataCriacao: "2025-05-22",
    dataTermino: "2025-11-05",
    anexos: ["Plano", "Material", "Orçamento"],
  },
  {
    titulo: "Iluminação Inteligente",
    descricao: "Postes com sensores e LED.",
    custo: "7.400.000 Kz",
    localizacao: "Talatona, Luanda",
    estado: "recusado",
    dataCriacao: "2025-01-08",
    dataTermino: "2025-06-30",
    anexos: ["Projeto", "Simulação", "Orçamento"],
  },
]